import type { CertificateTemplate } from "@/types/certificate"

export const CERTIFICATE_TEMPLATES: CertificateTemplate[] = [
  {
    id: "classic",
    name: "Classic",
    description: "Traditional certificate with elegant border and seal design",
    layout: {
      orientation: "landscape",
      size: [297, 210], // A4 landscape in mm
    },
    fields: {
      certificateTitle: {
        x: 148.5,
        y: 55,
        fontSize: 36,
        fontWeight: "bold",
        align: "center",
        color: "#1a1a1a",
      },
      awardMessage: {
        x: 148.5,
        y: 78,
        fontSize: 14,
        align: "center",
        color: "#4a5568",
      },
      recipientName: {
        x: 148.5,
        y: 100,
        fontSize: 32,
        fontWeight: "bold",
        align: "center",
      },
      subMessage: {
        x: 148.5,
        y: 130,
        fontSize: 14,
        align: "center",
        color: "#4a5568",
      },
      courseTitle: {
        x: 148.5,
        y: 150,
        fontSize: 18,
        align: "center",
      },
      date: {
        x: 148.5,
        y: 175,
        fontSize: 14,
        align: "center",
      },
      organization: {
        x: 148.5,
        y: 195,
        fontSize: 16,
        fontWeight: "bold",
        align: "center",
      },
      signaturePosition: {
        x: 240,
        y: 195,
        fontSize: 12,
        align: "center",
        color: "#4a5568",
      },
    },
    styles: {
      primaryColor: "#1a1a1a",
      secondaryColor: "#4a5568",
      backgroundColor: "#ffffff",
      borderColor: "#d4af37",
      borderWidth: 8,
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Clean, minimalist design perfect for contemporary certificates",
    layout: {
      orientation: "landscape",
      size: [297, 210],
    },
    fields: {
      certificateTitle: {
        x: 148.5,
        y: 50,
        fontSize: 32,
        fontWeight: "bold",
        align: "center",
        color: "#1e40af",
      },
      awardMessage: {
        x: 148.5,
        y: 73,
        fontSize: 12,
        align: "center",
        color: "#64748b",
      },
      recipientName: {
        x: 148.5,
        y: 95,
        fontSize: 28,
        fontWeight: "bold",
        align: "center",
        color: "#1e40af",
      },
      subMessage: {
        x: 148.5,
        y: 125,
        fontSize: 12,
        align: "center",
        color: "#64748b",
      },
      courseTitle: {
        x: 148.5,
        y: 145,
        fontSize: 16,
        align: "center",
        color: "#64748b",
      },
      date: {
        x: 148.5,
        y: 170,
        fontSize: 12,
        align: "center",
        color: "#94a3b8",
      },
      organization: {
        x: 148.5,
        y: 185,
        fontSize: 14,
        align: "center",
        color: "#475569",
      },
      signaturePosition: {
        x: 240,
        y: 185,
        fontSize: 11,
        align: "center",
        color: "#64748b",
      },
    },
    styles: {
      primaryColor: "#1e40af",
      secondaryColor: "#64748b",
      backgroundColor: "#ffffff",
      borderColor: "#e2e8f0",
      borderWidth: 2,
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Formal certificate with decorative elements and classic styling",
    layout: {
      orientation: "landscape",
      size: [297, 210],
    },
    fields: {
      certificateTitle: {
        x: 148.5,
        y: 53,
        fontSize: 34,
        fontWeight: "bold",
        align: "center",
        color: "#7c3aed",
      },
      awardMessage: {
        x: 148.5,
        y: 76,
        fontSize: 13,
        align: "center",
        color: "#6b7280",
      },
      recipientName: {
        x: 148.5,
        y: 98,
        fontSize: 30,
        fontWeight: "bold",
        align: "center",
        color: "#7c3aed",
      },
      subMessage: {
        x: 148.5,
        y: 128,
        fontSize: 13,
        align: "center",
        color: "#6b7280",
      },
      courseTitle: {
        x: 148.5,
        y: 148,
        fontSize: 17,
        align: "center",
        color: "#6b7280",
      },
      date: {
        x: 148.5,
        y: 168,
        fontSize: 13,
        align: "center",
        color: "#9ca3af",
      },
      organization: {
        x: 148.5,
        y: 193,
        fontSize: 15,
        fontWeight: "bold",
        align: "center",
        color: "#4b5563",
      },
      signaturePosition: {
        x: 240,
        y: 193,
        fontSize: 12,
        align: "center",
        color: "#6b7280",
      },
    },
    styles: {
      primaryColor: "#7c3aed",
      secondaryColor: "#6b7280",
      backgroundColor: "#fafafa",
      borderColor: "#d1d5db",
      borderWidth: 4,
    },
  },
  {
    id: "professional",
    name: "Professional",
    description: "Corporate-style certificate ideal for business and professional achievements",
    layout: {
      orientation: "landscape",
      size: [297, 210],
    },
    fields: {
      certificateTitle: {
        x: 148.5,
        y: 52,
        fontSize: 30,
        fontWeight: "bold",
        align: "center",
        color: "#0f172a",
      },
      awardMessage: {
        x: 148.5,
        y: 75,
        fontSize: 12,
        align: "center",
        color: "#334155",
      },
      recipientName: {
        x: 148.5,
        y: 97,
        fontSize: 26,
        fontWeight: "bold",
        align: "center",
        color: "#0f172a",
      },
      subMessage: {
        x: 148.5,
        y: 127,
        fontSize: 12,
        align: "center",
        color: "#334155",
      },
      courseTitle: {
        x: 148.5,
        y: 147,
        fontSize: 15,
        align: "center",
        color: "#334155",
      },
      date: {
        x: 148.5,
        y: 162,
        fontSize: 12,
        align: "center",
        color: "#64748b",
      },
      organization: {
        x: 148.5,
        y: 188,
        fontSize: 13,
        fontWeight: "bold",
        align: "center",
        color: "#1e293b",
      },
      signaturePosition: {
        x: 240,
        y: 188,
        fontSize: 11,
        align: "center",
        color: "#475569",
      },
      certificateNumber: {
        x: 250,
        y: 30,
        fontSize: 10,
        align: "right",
        color: "#94a3b8",
      },
    },
    styles: {
      primaryColor: "#0f172a",
      secondaryColor: "#334155",
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 3,
    },
  },
]

export function getTemplate(id: string): CertificateTemplate | undefined {
  return CERTIFICATE_TEMPLATES.find((t) => t.id === id)
}

